apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # this labels is for replicaset
  labels:
    project: roboshop
    environment: dev
    component: frontend
  annotations:
    kubernetes.io/change-cause: "version is 1.29"  
spec:
  replicas: 2
  selector:
    matchLabels:
      # these labels is for replicaset to select the pods
      project: roboshop
      environment: dev
      component: frontend
  template:
    metadata:
    # these for pod defination
      labels:
        project: roboshop
        environment: dev
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.6

